name: trustsight
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - cudatoolkit=11.8

  - transformers=4.35.2
  - tokenizers=0.14.1
  - sentencepiece=0.1.99

  - pandas=2.0.3
  - numpy=1.24.3
  - scikit-learn=1.3.0
  - scipy=1.11.1

  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.15.0

  - jupyter=1.0.0
  - ipykernel=6.25.0
  - notebook=7.0.2

  - tqdm=4.65.0
  - pyyaml=6.0.1
  - python-dotenv=1.0.0

  - pytest=7.4.0
  - pytest-cov=4.1.0

  - pip
  - pip:
    - kafka-python==2.0.2
    - aiokafka==0.8.1
    - confluent-kafka==2.2.0

    - boto3==1.28.57
    - awscli==1.29.57

    - xgboost==1.7.6
    - lightgbm==4.0.0

    - networkx==3.1
    - torch-geometric==2.3.1
    - dgl==1.1.2

    - fastapi==0.103.1
    - uvicorn==0.23.2
    - pydantic==1.10.12          # ✅ Downgraded for compatibility

    - wandb==0.15.11
    - tensorboard==2.14.0
    - loguru==0.7.2

    - great-expectations==0.17.19
    - pandera==0.16.1            # ✅ Now compatible with pydantic 1.x

    - onnx==1.14.1
    - onnxruntime==1.16.0

    - python-multipart==0.0.6
    - aiofiles==23.2.1
    - httpx==0.25.0
    - python-json-logger==2.0.7
